# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU CAN DO ALL THINGS, WELCOME.
- content: 每个清晨你都必须醒来，坐上地铁，路过他们的世界，人来人往，去属于你自己的地方。
bottom_saying: 会不会有那么一天，一次机缘巧合，就会改变我整个人生的方向
# Content
excerpt_link: Read More

#rss: /atom.xml

highlightjs: vs

#Works
works: 
- works_name: 必应
  works_url: https://www.bing.com/
- works_name: 谷歌
  works_url: https://www.google.com/
- works_name: Github
  works_url: https://www.github.com/
- works_name: 知乎
  works_url: https://www.zhihu.com/
- works_name: 豆瓣
  works_url: https://www.douban.com/
- works_name: 优酷
  works_url: https://www.youku.com/
- works_name: Youtube
  works_url: https://www.youtube.com/

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
#github: https://github.com/
#twitter: https://twitter.com/
#facebook: https://www.facebook.com/
#google: https://google.com/
#weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2017/05/19-Start
- num: 2
  word: 2017/06/03-简介
- num: 3
  word: 2017/06/03-博客内容书写基础知识
- num: 4
  word: 2017/06/03-草稿与主题
- num: 5
  word: 2017/06/03-书影短评
- num: 6
  word: 2017/06/03-书单与影单
- num: 7
  word: 2017/06/05-趣知识一
- num: 8
  word: More

#Links
links:
- name: 博客入门
  link: http://www.changewade.live/tags/博客入门/
- name: 书与影
  link: http://www.changewade.live/tags/书与影/
- name: 趣知识
  link: http://www.changewade.live/tags/趣知识/

