# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU CAN DO ALL THINGS, WELCOME.
- content: 每个清晨你都必须醒来，坐上地铁，路过他们的世界，人来人往，去属于你自己的地方。
bottom_saying: 会不会有那么一天，一次机缘巧合，就会改变我整个人生的方向
# Content
excerpt_link: Read More

#rss: /atom.xml

highlightjs: vs


#Links
links:
- name: Bing
  link: https://www.bing.com/
- name: Google
  link: https://www.google.com/
- name: Github
  link: https://www.github.com/
- name: 知乎
  link: https://www.zhihu.com/
- name: 豆瓣
  link: https://www.douban.com/
- name: 优酷
  link: https://www.youku.com/
- name: Youtube
  link: https://www.youtube.com/


#Works
works: 
- works_name: timeline
  works_url: http://www.changewade.live/timeline/
- works_name: 博客入门
  works_url: http://www.changewade.live/tags/博客入门/
- works_name: 书与影
  works_url: http://www.changewade.live/tags/书与影/
- works_name: 趣知识
  works_url: http://www.changewade.live/tags/趣知识/
- works_name: 文章
  works_url: http://www.changewade.live/tags/文章/


#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
#github: https://github.com/
#twitter: https://twitter.com/
#facebook: https://www.facebook.com/
#google: https://google.com/
#weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2017/05/19-Start
- num: 2
  word: 2017/06/03-简介
- num: 3
  word: 2017/06/03-博客内容书写基础知识
- num: 4
  word: 2017/06/03-草稿与主题
- num: 5
  word: 2017/06/03-书影短评
- num: 6
  word: 2017/06/03-书单与影单
- num: 7
  word: 2017/06/05-趣知识一
- num: 8
  word: More



